
import java.io.File;
import java.io.FileOutputStream;
import java.io.ObjectOutputStream;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author estudiante
 */
public class InterfazEmpleado extends javax.swing.JFrame {

    /**
     * Creates new form InterfazEmpleado
     */
    Pila a = new Pila();
    
    DefaultTableModel tabla = new DefaultTableModel();
    public InterfazEmpleado() {
        initComponents();
        limpiarFormEmpleado();
        // 
        
        this.tabla.addColumn("NOMBRE");
        this.tabla.addColumn("APELLIDO");
        this.tabla.addColumn("SEXO");
        this.tabla.addColumn("EDAD");
        this.tabla.addColumn("SUELDO");
        
        
        this.jTableEmpleado.setModel(tabla);
        
        this.setLocationRelativeTo(null);
        String nombre = this.jTextFieldNombre.getText();
        System.out.println(nombre);
        
        
        
        a.mostrar();
        
        
        // 
        this.jLabel3.setText("sexo");
        
        
        
    }
    void limpiarFormEmpleado(){
        this.jTextFieldNombre.setText("");
        this.jTextFieldApellido.setText("");
        this.jTextFieldEdad.setText("0");
        this.jTextFieldSueldo.setText("0");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ButtonGrupoSexo = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jTextFieldSueldo = new javax.swing.JTextField();
        jTextFieldEdad = new javax.swing.JTextField();
        jTextFieldNombre = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldApellido = new javax.swing.JTextField();
        jButtonGuardarPila = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableEmpleado = new javax.swing.JTable();
        jButtonEmpleadoJoven = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jRadioButtonFemenino = new javax.swing.JRadioButton();
        jRadioButtonMasculino = new javax.swing.JRadioButton();
        jRadioButtonOtros = new javax.swing.JRadioButton();
        jButtonVolverInicio = new javax.swing.JButton();
        jButtonAdicionar = new javax.swing.JButton();
        jProgressBarPila = new javax.swing.JProgressBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextFieldSueldo.setText("hola a todosç");

        jTextFieldEdad.setText("hola a todosç");

        jTextFieldNombre.setText("hola a todosç");

        jLabel1.setText("Nombre");

        jLabel2.setText("Apellido");

        jLabel3.setText("Sexo");

        jLabel4.setText("Edad");

        jLabel5.setText("Sueldo");

        jTextFieldApellido.setText("hola a todosç");

        jButtonGuardarPila.setText("Guardar Pila");
        jButtonGuardarPila.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGuardarPilaActionPerformed(evt);
            }
        });

        jTableEmpleado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableEmpleado);

        jButtonEmpleadoJoven.setText("Empleado Joven");
        jButtonEmpleadoJoven.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEmpleadoJovenActionPerformed(evt);
            }
        });

        jButton2.setText("Ordenar Empleado");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        ButtonGrupoSexo.add(jRadioButtonFemenino);
        jRadioButtonFemenino.setText("Femenino");

        ButtonGrupoSexo.add(jRadioButtonMasculino);
        jRadioButtonMasculino.setText("Masculino");

        ButtonGrupoSexo.add(jRadioButtonOtros);
        jRadioButtonOtros.setText("Otros");

        jButtonVolverInicio.setText("Volver");
        jButtonVolverInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVolverInicioActionPerformed(evt);
            }
        });

        jButtonAdicionar.setText("Adiconar");
        jButtonAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAdicionarActionPerformed(evt);
            }
        });

        jProgressBarPila.setMaximum(5);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jProgressBarPila, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(jTextFieldApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jRadioButtonOtros)
                                    .addComponent(jRadioButtonFemenino)
                                    .addComponent(jRadioButtonMasculino)))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel5)
                                    .addGap(23, 23, 23)
                                    .addComponent(jTextFieldSueldo, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addGap(31, 31, 31)
                                    .addComponent(jTextFieldEdad, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jButton2)
                                    .addComponent(jButtonEmpleadoJoven))
                                .addGap(18, 18, 18)
                                .addComponent(jButtonVolverInicio))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButtonGuardarPila)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonAdicionar)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 135, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel1))
                    .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jProgressBarPila, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel2))
                    .addComponent(jTextFieldApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jRadioButtonMasculino)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButtonFemenino)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButtonOtros)
                        .addGap(18, 18, 18)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel4))
                    .addComponent(jTextFieldEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel5))
                    .addComponent(jTextFieldSueldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonGuardarPila)
                            .addComponent(jButtonAdicionar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonEmpleadoJoven)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addComponent(jButtonVolverInicio))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(55, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 10, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonGuardarPilaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGuardarPilaActionPerformed
        String nomArch = "Empleado.dat";
        try{
            ObjectOutputStream arch = null;
            if(new File(nomArch).exists())
                arch = new AddObjectOutputStream(new FileOutputStream(nomArch, true));
            else
                arch = new ObjectOutputStream(new FileOutputStream(nomArch, true));
            
            
            arch.writeObject(a);
                arch.close();
            JOptionPane.showMessageDialog(null, "Pila Guardada en el archivo");
                
            
        } catch (Exception e) {
                
                
        }
        
        
        
        
        
        
    }//GEN-LAST:event_jButtonGuardarPilaActionPerformed
    
    public void mostrarTabla(){
        tabla.setNumRows(0);
            limpiarFormEmpleado();
            Pila aux = new Pila();
            while(!a.esVacia()){
                Empleado ee = (Empleado)a.eliminar();
                aux.adicionar((Object)ee);
                String datos[] = new String[5];
                datos[0] = ee.getNombre();
                datos[1] = ee.getApellido();
                datos[2] = ee.getSexo();
                datos[3] = ee.getEdad() + "";
                datos[4] = ee.getSueldo() + "";
                
                tabla.addRow(datos);
            }
            
            a.vaciar(aux);
            
    }
    private void jButtonEmpleadoJovenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEmpleadoJovenActionPerformed
        
        int mn = 1000000;
        Pila aux = new Pila();
        System.out.println("jovn");
        while(!a.esVacia()){    
            Empleado e1 = (Empleado)a.eliminar();
            e1.mostrar();
            if(mn > e1.getEdad()){
                mn = e1.getEdad();
            }
            aux.adicionar(e1);
            
        }
        System.out.println(mn);
        
        while(!aux.esVacia()){
            Empleado e1 = (Empleado)aux.eliminar();
            if(mn == e1.getEdad()){
                this.jTextFieldNombre.setText(e1.getNombre());
                this.jTextFieldApellido.setText(e1.getApellido());
                
                this.jTextFieldEdad.setText(e1.getEdad() + "");
                this.jTextFieldSueldo.setText(e1.getSueldo() + "");
            }
            a.adicionar(e1);
            
        }
    }//GEN-LAST:event_jButtonEmpleadoJovenActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Pila aux = new Pila();
        Pila resp = new Pila();
        System.out.println("datos antes de ordenar");
        a.mostrar();
        System.out.println("ordendnado");
        while(! a.esVacia()){
            Empleado mn = (Empleado) a.eliminar();
            aux.adicionar((Object)mn);
            while(! a.esVacia()){
                Empleado comp = (Empleado) a.eliminar();
                if(comp.getEdad() < mn.getEdad()  ){
                    mn = comp;
                }
                aux.adicionar((Object)comp);
            }
            
            while(! aux.esVacia()){
                Empleado comp = (Empleado) aux.eliminar();
                if(comp.getEdad() == mn.getEdad()  ){
                    resp.adicionar(comp);
                }else{
                    a.adicionar((Object)comp);
                }
            }
            
            
            
        }
        a.vaciar(resp);
        a.mostrar();
        mostrarTabla();
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButtonVolverInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVolverInicioActionPerformed
        // TODO add your handling code here:
        InterfazInicio ii = new InterfazInicio();
        ii.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonVolverInicioActionPerformed

    private void jButtonAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAdicionarActionPerformed
        // TODO add your handling code here:
        boolean okey = true;
            Empleado e = new Empleado();
            e.setNombre(this.jTextFieldNombre.getText());
            e.setApellido(this.jTextFieldApellido.getText());

            if(this.jRadioButtonFemenino.isSelected()){
                e.setSexo(this.jRadioButtonFemenino.getText().toString());
            }

            if(this.jRadioButtonMasculino.isSelected()){
                e.setSexo(this.jRadioButtonMasculino.getText().toString());
            }

            if(this.jRadioButtonOtros.isSelected()){
                e.setSexo(this.jRadioButtonOtros.getText().toString());
            }


            try {
                int edad = Integer.parseInt(this.jTextFieldEdad.getText());
                e.setEdad(edad);
            } catch (Exception e1) {
                JOptionPane.showMessageDialog(null, "Edad debe ser entero");
                okey = false;
            }

            try {
                double sueldo = Double.parseDouble(this.jTextFieldSueldo.getText());
                e.setSueldo(sueldo);
            } catch (Exception e1) {
                JOptionPane.showMessageDialog(null, "Sueldo debe ser decimal");
                okey = false;
            }


            if(okey){
                a.adicionar((Object)e);
                mostrarTabla();
                a.mostrar();
                JOptionPane.showMessageDialog(null, "Aniadido a la PIla");
                this.jProgressBarPila.setValue(this.jProgressBarPila.getValue() + 1);
                if(this.jProgressBarPila.getValue() == 5){
                    this.jButtonAdicionar.setEnabled(false);
                }

            }
        
    }//GEN-LAST:event_jButtonAdicionarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfazEmpleado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup ButtonGrupoSexo;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButtonAdicionar;
    private javax.swing.JButton jButtonEmpleadoJoven;
    private javax.swing.JButton jButtonGuardarPila;
    private javax.swing.JButton jButtonVolverInicio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JProgressBar jProgressBarPila;
    private javax.swing.JRadioButton jRadioButtonFemenino;
    private javax.swing.JRadioButton jRadioButtonMasculino;
    private javax.swing.JRadioButton jRadioButtonOtros;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableEmpleado;
    private javax.swing.JTextField jTextFieldApellido;
    private javax.swing.JTextField jTextFieldEdad;
    private javax.swing.JTextField jTextFieldNombre;
    private javax.swing.JTextField jTextFieldSueldo;
    // End of variables declaration//GEN-END:variables
}
